apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  namespace: default
  labels:
    app: k8s_python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: python:3.9-slim 
        ports:
        - containerPort: 9999
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: python-app-config
              key: APP_PORT
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: python-app-config
              key: APP_ENV